---
- name: Install Docker and Docker Compose on Ubuntu
  hosts: all
  become: yes
  vars:
    ubuntu_release: "noble"
    docker_user: "{{ ansible_user }}"
      
  tasks:
    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
        update_cache: yes

    - name: Add Docker's official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ubuntu_release }} stable"
        state: present

    - name: Install Docker Engine
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: yes

    - name: Add user to the Docker group
      ansible.builtin.shell: |
        sudo usermod -aG docker {{ docker_user }}

    - name: Ensure Docker service is started and enabled
      service:
        name: docker
        state: started
        enabled: yes